version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: halake-app
    volumes:
      - .:/var/www
    ports:
      - "8080:9000"
    networks:
      - halake-net

  nginx:
    image: nginx:alpine
    container_name: halake-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - halake-net

  mysql:
    image: mysql:8.0
    container_name: mysql-server
    ports:
      - "5052:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: halake_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app_pass_123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - halake-net

networks:
  halake-net:
    driver: bridge

volumes:
  mysql_data:
